export const GET_ACHATS_LIST="GET_ACHATS_LIST";
export const MEDICAMENT_LIST_REQUEST="MEDICAMENT_LIST_REQUEST";
export const MEDICAMENT_LIST_SUCCESS="MEDICAMENT_LIST_SUCCESS";
export const MEDICAMENT_LIST_FAIL="MEDICAMENT_LIST_FAIL";