//Ajouter commande
export const ACHAT_AJOUTER_REQUEST="ACHAT_AJOUTER_REQUEST";
export const ACHAT_AJOUTER_SUCCESS="ACHAT_AJOUTER_SUCCESS";
export const ACHAT_AJOUTER_FAIL="ACHAT_AJOUTER_FAIL";

//List achat
export const ACHAT_LIST_REQUEST="ACHAT_LIST_REQUEST";
export const ACHAT_LIST_SUCCESS="ACHAT_LIST_SUCCESS";
export const ACHAT_LIST_FAIL="ACHAT_LIST_FAIL";

