//Ajouter commande
export const COMMANDE_AJOUTER_REQUEST="COMMANDE_AJOUTER_REQUEST";
export const COMMANDE_AJOUTER_SUCCESS="COMMANDE_AJOUTER_SUCCESS";
export const COMMANDE_AJOUTER_FAIL="COMMANDE_AJOUTER_FAIL";