//Ajouter commande
export const COMMANDE_AJOUTER_REQUEST="COMMANDE_AJOUTER_REQUEST";
export const COMMANDE_AJOUTER_SUCCESS="COMMANDE_AJOUTER_SUCCESS";
export const COMMANDE_AJOUTER_FAIL="COMMANDE_AJOUTER_FAIL";

//list commande
export const COMMANDE_LIST_REQUEST="COMMANDE_LIST_REQUEST";
export const COMMANDE_LIST_SUCCESS="COMMANDE_LIST_SUCCESS";
export const COMMANDE_LIST_FAIL="COMMANDE_LIST_FAIL";