//Ajouter commande
export const EMPLOYER_AJOUTER_REQUEST="EMPLOYER_AJOUTER_REQUEST";
export const EMPLOYER_AJOUTER_SUCCESS="EMPLOYER_AJOUTER_SUCCESS";
export const EMPLOYER_AJOUTER_FAIL="EMPLOYER_AJOUTER_FAIL";

export const EMPLOYER_LIST_REQUEST="EMPLOYER_LIST_REQUEST";
export const EMPLOYER_LIST_SUCCESS="EMPLOYER_LIST_SUCCESS";
export const EMPLOYER_LIST_FAIL="EMPLOYER_LIST_FAIL";