export const FAMILLE_LIST_REQUEST="FAMILLE_LIST_REQUEST";
export const FAMILLE_LIST_SUCCESS="FAMILLE_LIST_SUCCESS";
export const FAMILLE_LIST_FAIL="FAMILLE_LIST_FAIL";

//supression Famille
export const FAMILLE_SUPPRIMER_REQUEST="FAMILLE_SUPPRIMER_REQUEST";
export const FAMILLE_SUPPRIMER_SUCCESS="FAMILLE_SUPPRIMER_SUCCESS";
export const FAMILLE_SUPPRIMER_FAIL="FAMILLE_SUPPRIMER_FAIL";

//Ajouter Famille
export const FAMILLE_AJOUTER_REQUEST="FAMILLE_AJOUTER_REQUEST";
export const FAMILLE_AJOUTER_SUCCESS="FAMILLE_AJOUTER_SUCCESS";
export const FAMILLE_AJOUTER_FAIL="FAMILLE_AJOUTER_FAIL";
export const FAMILLE_AJOUTER_RESET="FAMILLE_AJOUTER_RESET";

//Mofifier Famillle
export const FAMILLE_MODIFIER_REQUEST="FAMILLE_MODIFIER_REQUEST";
export const FAMILLE_MODIFIER_SUCCESS="FAMILLE_MODIFIER_SUCCESS";
export const FAMILLE_MODIFIER_FAIL="FAMILLE_MODIFIER_FAIL";
export const FAMILLE_MODIFIER_RESET="FAMILLE_MODIFIER_RESET";