export const FOURNISSEUR_LIST_REQUEST="FOURNISSEUR_LIST_REQUEST";
export const FOURNISSEUR_LIST_SUCCESS="FOURNISSEUR_LIST_SUCCESS";
export const FOURNISSEUR_LIST_FAIL="FOURNISSEUR_LIST_FAIL";

export const FOURNISSEUR_AJOUTER_REQUEST="FOURNISSEUR_AJOUTER_REQUEST";
export const FOURNISSEUR_AJOUTER_SUCCESS="FOURNISSEUR_AJOUTER_SUCCESS";
export const FOURNISSEUR_AJOUTER_FAIL="FOURNISSEUR_AJOUTER_FAIL";

export const FOURNISSEUR_SUPPRIMER_REQUEST="FOURNISSEUR_SUPPRIMER_REQUEST";
export const FOURNISSEUR_SUPPRIMER_SUCCESS="FOURNISSEUR_SUPPRIMER_SUCCESS";
export const FOURNISSEUR_SUPPRIMER_FAIL="FOURNISSEUR_SUPPRIMER_FAIL";