//Ajouter MEDICAMENT
export const MEDICAMENT_AJOUTER_REQUEST="MEDICAMENT_AJOUTER_REQUEST";
export const MEDICAMENT_AJOUTER_SUCCESS="MEDICAMENT_AJOUTER_SUCCESS";
export const MEDICAMENT_AJOUTER_FAIL="MEDICAMENT_AJOUTER_FAIL";
export const MEDICAMENT_AJOUTER_RESET="MEDICAMENT_AJOUTER_RESET";

//liste medicament
export const MEDICAMENT_LIST_REQUEST="MEDICAMENT_LIST_REQUEST";
export const MEDICAMENT_LIST_SUCCESS="MEDICAMENT_LIST_SUCCESS";
export const MEDICAMENT_LIST_FAIL="MEDICAMENT_LIST_FAIL";

export const MEDICAMENT_SUPPRIMER_REQUEST="MEDICAMENT_SUPPRIMER_REQUEST";
export const MEDICAMENT_SUPPRIMER_SUCCESS="MEDICAMENT_SUPPRIMER_SUCCESS";
export const MEDICAMENT_SUPPRIMER_FAIL="MEDICAMENT_SUPPRIMER_FAIL";

export const MEDICAMENT_FILTRER_REQUEST="MEDICAMENT_FILTRER_REQUEST";
export const MEDICAMENT_FILTRER_SUCCESS="MEDICAMENT_FILTRER_SUCCESS";
export const MEDICAMENT_FILTER_FAIL="MEDICAMENT_FILTER_FAIL";


//Mofifier Famillle
export const MEDICAMENT_MODIFIER_REQUEST="MEDICAMENT_MODIFIER_REQUEST";
export const MEDICAMENT_MODIFIER_SUCCESS="MEDICAMENT_MODIFIER_SUCCESS";
export const MEDICAMENT_MODIFIER_FAIL="MEDICAMENT_MODIFIER_FAIL";
export const MEDICAMENT_MODIFIER_RESET="MEDICAMENT_MODIFIER_RESET";