export const MEDICAMENT_LIST_REQUEST="MEDICAMENT_LIST_REQUEST";
export const MEDICAMENT_LIST_SUCCESS="MEDICAMENT_LIST_SUCCESS";
export const MEDICAMENT_LIST_FAIL="MEDICAMENT_LIST_FAIL";

export const MEDICAMENT_AJOUTER_SUCCESS="MEDICAMENT_AJOUTER_SUCCESS";