export const PANIER_AJOUTER_REQUEST="PANIER_AJOUTER_REQUEST";
export const PANIER_AJOUTER_SUCCESS="PANIER_AJOUTER_SUCCESS";
export const PANIER_AJOUTER_FAIL="PANIER_AJOUTER_FAIL";

export const PANIER_LIST_REQUEST="PANIER_LIST_REQUEST";
export const PANIER_LIST_SUCCESS="PANIER_LIST_SUCCESS";
export const PANIER_LIST_FAIL="PANIER_LIST_FAIL";