export const STASTMOIS_LIST_REQUEST="STASTMOIS_LIST_REQUEST";
export const STASTMOIS_LIST_SUCCESS="STASTMOIS_LIST_SUCCESS";
export const STASTMOIS_LIST_FAIL="STASTMOIS_LIST_FAIL";

export const STASTANNEES_LIST_REQUEST="STASTANNEES_LIST_REQUEST";
export const STASTANNEES_LIST_SUCCESS="STASTANNEES_LIST_SUCCESS";
export const STASTANNEES_LIST_FAIL="STASTANNEES_LIST_FAIL";