export const STOCK_LIST_REQUEST="STOCK_LIST_REQUEST";
export const STOCK_LIST_SUCCESS="STOCK_LIST_SUCCESS";
export const STOCK_LIST_FAIL="STOCK_LIST_FAIL"

export const STOCK_FILTRER_REQUEST="STOCK_FILTRER_REQUEST";
export const STOCK_FILTRER_SUCCESS="STOCK_FILTRER_SUCCESS";
export const STOCK_FILTER_FAIL="STOCK_FILTER_FAIL";