//Ajouter vente
export const VENTE_AJOUTER_REQUEST="VENTE_AJOUTER_REQUEST";
export const VENTE_AJOUTER_SUCCESS="VENTE_AJOUTER_SUCCESS";
export const VENTE_AJOUTER_FAIL="VENTE_AJOUTER_FAIL";
//List vente
export const VENTE_LIST_REQUEST="VENTE_LIST_REQUEST";
export const VENTE_LIST_SUCCESS="VENTE_LIST_SUCCESS";
export const VENTE_LIST_FAIL="VENTE_LIST_FAIL";
