//Ajouter commande
export const VENTEMEDICAMENT_AJOUTER_REQUEST="VENTEMEDICAMENT_AJOUTER_REQUEST";
export const VENTEMEDICAMENT_AJOUTER_SUCCESS="VENTEMEDICAMENT_AJOUTER_SUCCESS";
export const VENTEMEDICAMENT_AJOUTER_FAIL="VENTEMEDICAMENT_AJOUTER_FAIL";

//list commande
export const VENTEMEDICAMENT_LIST_REQUEST="VENTEMEDICAMENT_LIST_REQUEST";
export const VENTEMEDICAMENT_LIST_SUCCESS="VENTEMEDICAMENT_LIST_SUCCESS";
export const VENTEMEDICAMENT_LIST_FAIL="VENTEMEDICAMENT_LIST_FAIL";